name: CI/CD Pipeline with Security Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    
    - name: Run tests
      run: mvn clean test
    
    - name: Run SpotBugs Security Analysis (SAST)
      run: mvn compile spotbugs:check
      continue-on-error: false

    - name: Run OWASP Dependency Check (SCA)
      run: mvn dependency-check:check
      continue-on-error: false
    
    - name: Build application
      run: mvn clean package -DskipTests
